pipeline {
    
	agent any
/*	
	tools {
        maven "maven3"
    }
*/	
    environment {
        // NEXUS_VERSION = "nexus3"
        // NEXUS_PROTOCOL = "http"
        // NEXUS_URL = "172.31.40.209:8081"
        // NEXUS_REPOSITORY = "vprofile-release"
	    // NEXUS_REPOGRP_ID    = "vprofile-grp-repo"
        // NEXUS_CREDENTIAL_ID = "nexuslogin"
        ARTVERSION = "${env.BUILD_ID}"
        registryCredential = 'ecr:us-east-1:awscreds'
        appRegistry = '167929874870.dkr.ecr.us-east-1.amazonaws.com/vprofileappimg'
        vprofileRegistry = "https://167929874870.dkr.ecr.us-east-1.amazonaws.com/vprofileappimg"
    }
	
    stages{
        
        stage('BUILD'){
            steps {
                sh 'mvn clean install -DskipTests'
            }
            post {
                success {
                    echo 'Now Archiving...'
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        
        stage('Build App Image'){
              steps{
                script{
                    dockerImage = docker.build(appRegistry , "./Docker-files/app/multistage/")
                }

              }
        }
        stage ('Upload App Image'){
            steps{
                script{
                    docker.withRegistry( vprofileRegistry, registryCredential ){
                        dockerImage.push("$BUILD_NUMBER")
                        dockerImage.push('latest')
                    }
                }
            }

        }

	

	
       

        


    }


}
